// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGtbpHBS023T_8iqgY6qMpcLldJx-i1A',
    appId: '1:780104590816:web:97c742c2f28856a53c3785',
    messagingSenderId: '780104590816',
    projectId: 'ecotracker-esof',
    authDomain: 'ecotracker-esof.firebaseapp.com',
    storageBucket: 'ecotracker-esof.firebasestorage.app',
    measurementId: 'G-LNHHQCGF2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU9Tz8UCTgK1mbQjFJDWZE1a7pB4TWcCk',
    appId: '1:780104590816:android:12b7a9c70a4b11f03c3785',
    messagingSenderId: '780104590816',
    projectId: 'ecotracker-esof',
    storageBucket: 'ecotracker-esof.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiEYOLNfOARFrSpTK3jozbGzYsNZTNPdc',
    appId: '1:780104590816:ios:10631879207ee8c63c3785',
    messagingSenderId: '780104590816',
    projectId: 'ecotracker-esof',
    storageBucket: 'ecotracker-esof.firebasestorage.app',
    iosBundleId: 'com.esof.ecotracker',
  );
}
