name: eco_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  firebase_database: ^11.3.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/tips.json
